version: '3.8'
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.14-management-alpine
    environment:
      RABBITMQ_PID_FILE: /var/lib/rabbitmq/mnesia/rabbitmq
      # RABBITMQ_USER: myuser
      # RABBITMQ_PASSWORD: mypass
      # RABBITMQ_VHOST: myvhost
    volumes:
        - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - ./volumes/rabbitmq/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - localnet
      - marketplacenet

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: DBPassword
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - ./volumes/mariadb/:/var/lib/mysql
    # build:
    #   context: .
      # args:
      #   - haracter-set-client-handshake=FALSE
      #   - character-set-server=utf8mb4
      #   - collation-server=utf8mb4_unicode_ci
      #   - innodb-read-only-compressed=OFF
      #   - default-character-set=utf8mb4
    networks:
      - marketplacenet
      - localnet

  redis:
    container_name: redis
    image: docker.io/bitnami/redis:6.0.15
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - './volumes/redis:/bitnami/redis/data'
    networks:
      - marketplacenet
      - localnet

networks:
  localnet:
    external: true
  marketplacenet:
    external: true